#define SECRET_SSID "# Wifi Kısmı"
#define SECRET_PASS "# Şifre Kısmı"

#define SECRET_CH_ID_WEATHER_STATION 12397

#define SECRET_CH_ID_COUNTER 1338874
#define SECRET_READ_APIKEY_COUNTER "LT3CGD9ASCQ1NZRP"
